matdyn.ShaderParamKeyMaxLength = 100
matdyn.ShaderParamValueMaxLength = 200

matdyn.ShaderParamBlacklist = {
    PROXIES = true
}

matdyn.ShaderInfo = {
    ['Aftershock_dx9'] = {
        "COLORTINT",
        "REFRACTAMOUNT",
        "NORMALMAP",
        "BUMPFRAME",
        "BUMPTRANSFORM",
        "SILHOUETTETHICKNESS",
        "SILHOUETTECOLOR",
        "GROUNDMIN",
        "GROUNDMAX",
        "BLURAMOUNT",
        "TIME",
    },
    ['Bik'] = {
        "YTEXTURE",
        "ATEXTURE",
        "CRTEXTURE",
        "CBTEXTURE",
    },
    ['Black'] = {
    },
    ['Blob_dx9'] = {
        "BACKSURFACE",
        "NORMALMAP",
        "SPECMASKTEXTURE",
        "LIGHTWARPTEXTURE",
        "FRESNELWARPTEXTURE",
        "OPACITYTEXTURE",
        "UVSCALE",
        "BUMPSTRENGTH",
        "FRESNELBUMPSTRENGTH",
        "TRANSLUCENTFRESNELMINMAXEXP",
        "INTERIOR",
        "INTERIORFOGSTRENGTH",
        "INTERIORFOGLIMIT",
        "INTERIORFOGNORMALBOOST",
        "INTERIORBACKGROUNDBOOST",
        "INTERIORAMBIENTSCALE",
        "INTERIORBACKLIGHTSCALE",
        "INTERIORCOLOR",
        "INTERIORREFRACTSTRENGTH",
        "INTERIORREFRACTBLUR",
        "DIFFUSEBOOST",
        "PHONGEXPONENT",
        "PHONGBOOST",
        "PHONGEXPONENT2",
        "PHONGBOOST2",
        "RIMLIGHTEXPONENT",
        "RIMLIGHTBOOST",
        "BASECOLORTINT",
        "SELFILLUMFRESNEL",
        "SELFILLUMFRESNELMINMAXEXP",
        "SELFILLUMTINT",
        "UVPROJOFFSET",
        "BBMIN",
        "BBMAX",
        "ARMATURE",
        "ARMCOLOR",
        "ARMWIDEN",
        "ARMWIDTHEXP",
        "ARMWIDTHSCALE",
        "ARMWIDTHBIAS",
        "ANIMATEARMPULSES",
        "GLOWSCALE",
        "PULSE",
        "CONTACTSHADOWS",
        "VOLUMETEXTURETEST",
        "BUMPFRAME",
    },
    ['Character'] = {
        "RIMLIGHTEXPONENT",
        "RIMLIGHTBOOST",
        "RIMLIGHTALBEDO",
        "SHADOWRIMBOOST",
    },
    ['CharacterSSAO'] = {
    },
    ['Cloak_DX90'] = {
        "COLOR",
        "ALPHA",
        "REFRACTAMOUNT",
        "REFRACTTINT",
        "NORMALMAP",
        "BUMPFRAME",
        "BUMPTRANSFORM",
        "TIME",
        "REFRACTTINTTEXTURE",
        "REFRACTTINTTEXTUREFRAME",
        "FRESNELREFLECTION",
        "NOWRITEZ",
        "MASKED",
        "CLOAKFACTOR",
        "LIGHTWARPTEXTURE",
        "PHONGEXPONENT",
        "PHONGTINT",
        "PHONGALBEDOTINT",
        "PHONGFRESNELRANGES",
        "PHONGBOOST",
        "PHONGEXPONENTTEXTURE",
        "RIMLIGHT",
        "RIMLIGHTEXPONENT",
        "RIMLIGHTBOOST",
        "RIMMASK",
    },
    ['Cloud_dx9'] = {
        "BASETEXTURE",
        "CLOUDALPHATEXTURE",
        "CLOUDSCALE",
        "MASKSCALE",
    },
    ['Grass'] = {
        "DUMMYPARAM",
    },
    ['CustomCharacter'] = {
    },
    ['CustomClothing'] = {
    },
    ['CustomWeapon_dx9'] = {
        "SURFACETEXTURE",
        "AOTEXTURE",
        "MASKSTEXTURE",
        "POSTEXTURE",
        "GRUNGETEXTURE",
        "WEARTEXTURE",
        "PAINTTEXTURE",
        "EXPTEXTURE",
        "CAMOCOLOR0",
        "CAMOCOLOR1",
        "CAMOCOLOR2",
        "CAMOCOLOR3",
        "BASEDIFFUSEOVERRIDE",
        "PHONGEXPONENT",
        "WEARPROGRESS",
        "PHONGALBEDOBOOST",
        "PHONGINTENSITY",
        "PAINTSTYLE",
        "EXPONENTMODE",
        "PATTERNTEXTURETRANSFORM",
        "WEARTEXTURETRANSFORM",
        "GRUNGETEXTURETRANSFORM",
        "PHONGALBEDOFACTOR",
        "PREVIEW",
        "PHONGFRESNELRANGES",
        "PHONGALBEDOTINT",
        "PHONGBOOST",
        "PAINTPHONGALBEDOBOOST",
        "PREVIEWWEAPONOBJSCALE",
        "PREVIEWWEAPONUVSCALE",
        "PREVIEWIGNOREWEAPONSCALE",
    },
    ['DebugTextureView_dx9'] = {
        "SHOWALPHA",
    },
    ['Detail'] = {
    },
    ['Embroider'] = {
        "NCOLORS",
        "COLORGAMMA",
        "TEXTUREMODE",
    },
    ['Eyeball'] = {
        "BASETEXTURE",
        "BASETEXTURETRANSFORM",
    },
    ['EyeGlint_dx9'] = {
    },
    ['Eyes_dx9'] = {
        "IRIS",
        "IRISFRAME",
        "GLINT",
        "EYEORIGIN",
        "EYEUP",
        "IRISU",
        "IRISV",
        "GLINTU",
        "GLINTV",
        "DILATION",
    },
    ['EyeRefract_dx9'] = {
        "IRIS",
        "IRISFRAME",
        "CORNEATEXTURE",
        "AMBIENTOCCLTEXTURE",
        "ENVMAP",
        "EYEORIGIN",
        "IRISU",
        "IRISV",
        "DILATION",
        "GLOSSINESS",
        "SPHERETEXKILLCOMBO",
        "RAYTRACESPHERE",
        "PARALLAXSTRENGTH",
        "CORNEABUMPSTRENGTH",
        "AMBIENTOCCLCOLOR",
        "AMBIENTOCCLUSION",
        "EYEBALLRADIUS",
        "LIGHTWARPTEXTURE",
        "CLOAKPASSENABLED",
        "CLOAKFACTOR",
        "CLOAKCOLORTINT",
        "REFRACTAMOUNT",
        "EMISSIVEBLENDENABLED",
        "EMISSIVEBLENDSCROLLVECTOR",
        "EMISSIVEBLENDSTRENGTH",
        "EMISSIVEBLENDTINT",
    },
    ['floatcombine_autoexpose'] = {
        "SHARPNESS",
        "WOODCUT",
        "BLOOMAMOUNT",
        "BLOOMEXPONENT",
        "ALPHASHARPENFACTOR",
        "AUTOEXPOSE_MIN",
        "AUTOEXPOSE_MAX",
    },
    ['hsl_filmgrain_pass1'] = {
    },
    ['hsl_filmgrain_pass2'] = {
    },
    ['IceSurface_dx9'] = {
        "BACKSURFACE",
        "NORMALMAP",
        "SPECMASKTEXTURE",
        "LIGHTWARPTEXTURE",
        "FRESNELWARPTEXTURE",
        "OPACITYTEXTURE",
        "UVSCALE",
        "BUMPSTRENGTH",
        "FRESNELBUMPSTRENGTH",
        "TRANSLUCENTFRESNELMINMAXEXP",
        "INTERIOR",
        "INTERIORFOGSTRENGTH",
        "INTERIORFOGLIMIT",
        "INTERIORFOGNORMALBOOST",
        "INTERIORBACKGROUNDBOOST",
        "INTERIORAMBIENTSCALE",
        "INTERIORBACKLIGHTSCALE",
        "INTERIORCOLOR",
        "INTERIORREFRACTSTRENGTH",
        "INTERIORREFRACTBLUR",
        "DIFFUSESCALE",
        "PHONGEXPONENT",
        "PHONGBOOST",
        "PHONGEXPONENT2",
        "PHONGBOOST2",
        "RIMLIGHTEXPONENT",
        "RIMLIGHTBOOST",
        "BASECOLORTINT",
        "ENVMAPTINT",
        "UVPROJOFFSET",
        "BBMIN",
        "BBMAX",
        "CONTACTSHADOWS",
        "BUMPFRAME",
    },
    ['LightmappedReflective_DX90'] = {
        "REFRACTTEXTURE",
        "REFLECTTEXTURE",
        "REFRACTAMOUNT",
        "REFRACTTINT",
        "REFLECTAMOUNT",
        "REFLECTTINT",
        "NORMALMAP",
        "BUMPFRAME",
        "BUMPTRANSFORM",
        "ENVMAPMASK",
        "REFLECTANCE",
    },
    ['LightShafts_dx9'] = {
        "WORLDTOTEXTURE",
        "FLASHLIGHTCOLOR",
        "ATTENFACTORS",
        "ORIGINFARZ",
        "QUATORIENTATION",
        "SHADOWFILTERSIZE",
        "SHADOWATTEN",
        "SHADOWJITTERSEED",
        "UBERLIGHT",
        "ENABLESHADOWS",
        "NOISESTRENGTH",
        "UBERNEARFAR",
        "UBERHEIGHTWIDTH",
        "UBERROUNDNESS",
        "FLASHLIGHTTIME",
        "NUMPLANES",
        "VOLUMETRICINTENSITY",
    },
    ['Multiblend_DX90'] = {
        "ROTATION",
        "SCALE",
        "ROTATION2",
        "SCALE2",
        "ROTATION3",
        "SCALE3",
        "ROTATION4",
        "SCALE4",
    },
    ['paintblob_dx9'] = {
        "BACKSURFACE",
        "NORMALMAP",
        "SPECMASKTEXTURE",
        "LIGHTWARPTEXTURE",
        "FRESNELWARPTEXTURE",
        "OPACITYTEXTURE",
        "UVSCALE",
        "BUMPSTRENGTH",
        "FRESNELBUMPSTRENGTH",
        "TRANSLUCENTFRESNELMINMAXEXP",
        "INTERIOR",
        "INTERIORFOGSTRENGTH",
        "INTERIORBACKGROUNDBOOST",
        "INTERIORAMBIENTSCALE",
        "INTERIORBACKLIGHTSCALE",
        "INTERIORREFRACTSTRENGTH",
        "DIFFUSESCALE",
        "PHONGEXPONENT",
        "PHONGBOOST",
        "PHONGEXPONENT2",
        "PHONGBOOST2",
        "RIMLIGHTEXPONENT",
        "RIMLIGHTBOOST",
        "BASECOLORTINT",
        "UVPROJOFFSET",
        "BBMIN",
        "BBMAX",
        "CONTACTSHADOWS",
        "BUMPFRAME",
    },
    ['PortalRefract_dx9'] = {
        "STAGE",
        "PORTALOPENAMOUNT",
        "PORTALSTATIC",
        "TEXTURETRANSFORM",
        "PORTALCOLORGRADIENTDARK",
        "PORTALCOLORGRADIENTLIGHT",
        "PORTALCOLORSCALE",
        "TIME",
        "USEONSTATICPROP",
    },
    ['Projected_DX90'] = {
    },
    ['Prototype_dx9'] = {
        "BUMPFRAME",
    },
    ['ProtoIce_dx9'] = {
        "BUMPFRAME",
        "SSBUMP",
    },
    ['Refract_DX90'] = {
        "COLOR",
        "ALPHA",
        "REFRACTAMOUNT",
        "REFRACTTINT",
        "NORMALMAP",
        "NORMALMAP2",
        "BUMPFRAME",
        "BUMPFRAME2",
        "BUMPTRANSFORM",
        "BUMPTRANSFORM2",
        "TIME",
        "BLURAMOUNT",
        "FADEOUTONSILHOUETTE",
        "ENVMAP",
        "ENVMAPFRAME",
        "ENVMAPTINT",
        "ENVMAPCONTRAST",
        "ENVMAPSATURATION",
        "REFRACTTINTTEXTURE",
        "REFRACTTINTTEXTUREFRAME",
        "FRESNELREFLECTION",
        "NOWRITEZ",
        "MASKED",
        "NOVIEWPORTFIXUP",
        "MIRRORABOUTVIEWPORTEDGES",
        "MAGNIFYENABLE",
        "MAGNIFYCENTER",
        "MAGNIFYSCALE",
        "LOCALREFRACT",
        "LOCALREFRACTDEPTH",
    },
    ['Sample4x4_Blend'] = {
        "PIXSHADER",
    },
    ['Sky_HDR_DX9'] = {
        "COLOR",
    },
    ['SolidEnergy_dx9'] = {
        "DETAIL1",
        "DETAIL1SCALE",
        "DETAIL1FRAME",
        "DETAIL1BLENDMODE",
        "DETAIL1BLENDFACTOR",
        "DETAIL1TEXTURETRANSFORM",
        "DETAIL2",
        "DETAIL2SCALE",
        "DETAIL2FRAME",
        "DETAIL2BLENDMODE",
        "DETAIL2BLENDFACTOR",
        "DETAIL2TEXTURETRANSFORM",
        "TANGENTTOPACITYRANGES",
        "TANGENTSOPACITYRANGES",
        "FRESNELOPACITYRANGES",
        "NEEDSTANGENTT",
        "NEEDSTANGENTS",
        "NEEDSNORMALS",
        "DEPTHBLEND",
        "DEPTHBLENDSCALE",
        "FLOWMAPFRAME",
        "FLOWMAPSCROLLRATE",
        "OUTPUTINTENSITY",
    },
    ['SplineRope'] = {
        "SHADERSRGBREAD360",
        "SHADOWDEPTH",
        "BUMPMAP",
        "TILING",
        "ALPHATESTREFERENCE",
    },
    ['Teeth_DX9'] = {
        "ILLUMFACTOR",
        "FORWARD",
        "BUMPMAP",
        "PHONGEXPONENT",
    },
    ['UnlitGeneric'] = {
        "ALBEDO",
        "DETAIL",
        "DETAILFRAME",
        "DETAILSCALE",
        "ENVMAP",
        "ENVMAPMASK",
        "ENVMAPMASKFRAME",
        "ENVMAPMASKTRANSFORM",
        "ENVMAPTINT",
        "ENVMAPCONTRAST",
        "ENVMAPSATURATION",
        "ALPHATESTREFERENCE",
        "VERTEXALPHATEST",
        "HDRCOLORSCALE",
        "PHONGEXPONENT",
        "PHONGTINT",
        "PHONGALBEDOTINT",
        "LIGHTWARPTEXTURE",
        "PHONGWARPTEXTURE",
        "PHONGFRESNELRANGES",
        "PHONGBOOST",
        "PHONGEXPONENTTEXTURE",
        "PHONG",
        "DETAILBLENDMODE",
        "DETAILBLENDFACTOR",
        "DETAILTEXTURETRANSFORM",
        "DECALBLENDMODE",
        "DISTANCEALPHA",
        "DISTANCEALPHAFROMDETAIL",
        "SOFTEDGES",
        "SCALEEDGESOFTNESSBASEDONSCREENRES",
        "EDGESOFTNESSSTART",
        "EDGESOFTNESSEND",
        "GLOW",
        "GLOWCOLOR",
        "GLOWALPHA",
        "GLOWSTART",
        "GLOWEND",
        "GLOWX",
        "GLOWY",
        "OUTLINE",
        "OUTLINECOLOR",
        "OUTLINEALPHA",
        "OUTLINESTART0",
        "OUTLINESTART1",
        "OUTLINEEND0",
        "OUTLINEEND1",
        "SCALEOUTLINESOFTNESSBASEDONSCREENRES",
        "SEPARATEDETAILUVS",
        "GAMMACOLORREAD",
        "LINEARWRITE",
        "RECEIVEFLASHLIGHT",
        "SINGLEPASSFLASHLIGHT",
        "DISPLACEMENTMAP",
        "SHADERSRGBREAD360",
    },
    ['UnlitTwoTexture_DX9'] = {
        "TEXTURE2",
        "FRAME2",
        "TEXTURE2TRANSFORM",
        "CROSSHAIRMODE",
        "CROSSHAIRCOLORTINT",
        "CROSSHAIRCOLORADAPT",
        "CLOAKPASSENABLED",
        "CLOAKFACTOR",
        "CLOAKCOLORTINT",
        "REFRACTAMOUNT",
    },
    ['UnLitWorld_ScreenSample'] = {
    },
    ['VertexLitGeneric'] = {
        "ALBEDO",
        "COMPRESS",
        "STRETCH",
        "SELFILLUMTINT",
        "DETAIL",
        "DETAILFRAME",
        "DETAILSCALE",
        "ENVMAP",
        "ENVMAPFRAME",
        "ENVMAPMASK",
        "ENVMAPMASKFRAME",
        "ENVMAPMASKTRANSFORM",
        "ENVMAPTINT",
        "BUMPMAP",
        "BUMPCOMPRESS",
        "BUMPSTRETCH",
        "BUMPFRAME",
        "BUMPTRANSFORM",
        "ENVMAPCONTRAST",
        "ENVMAPSATURATION",
        "SELFILLUMFRESNEL",
        "SELFILLUMFRESNELMINMAXEXP",
        "SELFILLUMMASKSCALE",
        "SELFILLUMFRESNELENABLEDTHISFRAME",
        "ALPHATESTREFERENCE",
        "ALLOWFENCERENDERSTATEHACK",
        "FLASHLIGHTNOLAMBERT",
        "LOWQUALITYFLASHLIGHTSHADOWS",
        "DISABLECSMLOOKUP",
        "AMBIENTONLY",
        "PHONGEXPONENT",
        "PHONGTINT",
        "PHONGALBEDOTINT",
        "LIGHTWARPTEXTURE",
        "PHONGWARPTEXTURE",
        "PHONGFRESNELRANGES",
        "PHONGBOOST",
        "PHONGALBEDOBOOST",
        "PHONGEXPONENTTEXTURE",
        "PHONG",
        "FORCEPHONG",
        "BASEMAPALPHAPHONGMASK",
        "INVERTPHONGMASK",
        "ENVMAPFRESNEL",
        "SELFILLUMMASK",
        "BASEMAPLUMINANCEPHONGMASK",
        "DETAILBLENDMODE",
        "DETAILBLENDFACTOR",
        "DETAILTINT",
        "DETAILTEXTURETRANSFORM",
        "RIMLIGHT",
        "RIMLIGHTEXPONENT",
        "RIMLIGHTBOOST",
        "RIMMASK",
        "SEAMLESS_BASE",
        "SEAMLESS_DETAIL",
        "SEAMLESS_SCALE",
        "EMISSIVEBLENDENABLED",
        "EMISSIVEBLENDSCROLLVECTOR",
        "EMISSIVEBLENDSTRENGTH",
        "EMISSIVEBLENDTINT",
        "TIME",
        "CLOAKPASSENABLED",
        "CLOAKFACTOR",
        "CLOAKCOLORTINT",
        "REFRACTAMOUNT",
        "FLESHINTERIORENABLED",
        "FLESHBORDERNOISESCALE",
        "FLESHDEBUGFORCEFLESHON",
        "FLESHEFFECTCENTERRADIUS1",
        "FLESHEFFECTCENTERRADIUS2",
        "FLESHEFFECTCENTERRADIUS3",
        "FLESHEFFECTCENTERRADIUS4",
        "FLESHSUBSURFACETINT",
        "FLESHBORDERWIDTH",
        "FLESHBORDERSOFTNESS",
        "FLESHBORDERTINT",
        "FLESHGLOBALOPACITY",
        "FLESHGLOSSBRIGHTNESS",
        "FLESHSCROLLSPEED",
        "SEPARATEDETAILUVS",
        "LINEARWRITE",
        "SHADERSRGBREAD360",
        "SHADERSRGBREAD360",
        "AMBIENTOCCLUSION",
        "DISPLACEMENTMAP",
        "DISPLACEMENTWRINKLE",
        "BLENDTINTBYBASEALPHA",
        "NOTINT",
        "DESATURATEWITHBASEALPHA",
        "ALLOWDIFFUSEMODULATION",
        "ENVMAPFRESNELMINMAXEXP",
        "BASEALPHAENVMAPMASKMINMAXEXP",
        "PHONGDISABLEHALFLAMBERT",
        "TREESWAY",
        "TREESWAYHEIGHT",
        "TREESWAYSTARTHEIGHT",
        "TREESWAYRADIUS",
        "TREESWAYSTARTRADIUS",
        "TREESWAYSPEED",
        "TREESWAYSPEEDHIGHWINDMULTIPLIER",
        "TREESWAYSTRENGTH",
        "TREESWAYSCRUMBLESPEED",
        "TREESWAYSCRUMBLESTRENGTH",
        "TREESWAYSCRUMBLEFREQUENCY",
        "TREESWAYFALLOFFEXP",
        "TREESWAYSCRUMBLEFALLOFFEXP",
        "TREESWAYSPEEDLERPSTART",
        "TREESWAYSPEEDLERPEND",
        "TREESWAYSTATIC",
        "DECALBLENDMODE",
        "ENVMAPLIGHTSCALE",
        "ENVMAPLIGHTSCALEMINMAX",
        "BLENDWITHSMOKEGRENADE",
        "BLENDWITHSMOKEGRENADEPOSENTITY",
        "BLENDWITHSMOKEGRENADEPOSSMOKE",
        "MODELDECALIGNOREZ",
        "ENVMAPMASKINTINTMASKTEXTURE",
    },
    ['VolumeClouds_dx9'] = {
        "REFRACTAMOUNT",
        "TIME",
    },
    ['Water_DuDv'] = {
        "BUMPFRAME",
        "BUMPTRANSFORM",
        "REFRACTAMOUNT",
        "REFRACTTINT",
    },
    ['WeaponDecal_dx9'] = {
        "THIRDPERSON",
        "AOTEXTURE",
        "EXPTEXTURE",
        "NORMALMAP",
        "GRUNGETEXTURE",
        "WEARTEXTURE",
        "ANISODIRTEXTURE",
        "MIRRORHORIZONTAL",
        "WEARREMAPMIN",
        "WEARREMAPMID",
        "WEARREMAPMAX",
        "WEARWIDTHMIN",
        "WEARWIDTHMAX",
        "ALPHAMASK",
        "FASTWEARTHRESHOLD",
        "HIGHLIGHT",
        "HIGHLIGHTCYCLE",
        "PEEL",
        "ENVMAP",
        "ENVMAPTINT",
        "ALPHA",
        "PHONG",
        "PHONGEXPONENT",
        "PHONGFRESNELRANGES",
        "PHONGALBEDOTINT",
        "PHONGBOOST",
        "PHONGALBEDOBOOST",
        "DECALSTYLE",
        "PATTERNTEXTURETRANSFORM",
        "PATTERNROTATION",
        "PATTERNSCALE",
        "COLORTINT4",
        "COLORTINT3",
        "COLORTINT2",
        "COLORTINT",
        "WEARBIAS",
        "UNWEARSTRENGTH",
        "WEARPROGRESS",
        "GRUNGESCALE",
        "DESATBASETINT",
    },
    ['worldimposter'] = {
    },
    ['WorldVertexAlpha'] = {
    },
    ['WorldVertexTransition_DX9'] = {
        "SELFILLUMTINT",
        "DETAIL",
        "DETAILFRAME",
        "DETAILSCALE",
        "DETAIL2",
        "DETAILFRAME2",
        "DETAILSCALE2",
        "DETAILBLENDMODE",
        "DETAILBLENDFACTOR",
        "DETAILTINT",
        "DETAILBLENDFACTOR2",
        "DETAILTINT2",
        "ENVMAP",
        "ENVMAPMASK",
        "ENVMAPMASKTRANSFORM",
        "ENVMAPTINT",
        "BUMPMAP",
        "BUMPFRAME",
        "BUMPTRANSFORM",
        "ENVMAPCONTRAST",
        "ENVMAPSATURATION",
        "FRESNELREFLECTION",
        "NODIFFUSEBUMPLIGHTING",
        "BUMPMAP2",
        "BUMPFRAME2",
        "BUMPTRANSFORM2",
        "BUMPMASK",
        "BASETEXTURE2",
        "FRAME2",
        "SSBUMP",
        "BUMP_FORCE_ON",
        "SEAMLESS_SCALE",
        "ENVMAPANISOTROPY",
        "ENVMAPANISOTROPYSCALE",
        "ENVMAPLIGHTSCALE",
        "ENVMAPLIGHTSCALEMINMAX",
        "PHONG",
        "PHONGEXPONENT",
        "PHONGEXPONENT2",
        "PHONGBASETINT",
        "PHONGBASETINT2",
        "PHONGMASKCONTRASTBRIGHTNESS",
        "PHONGMASKCONTRASTBRIGHTNESS2",
        "PHONGAMOUNT",
        "PHONGAMOUNT2",
        "DROPSHADOWOPACITY",
        "DROPSHADOWSCALE",
        "DROPSHADOWHIGHLIGHTSCALE",
        "DROPSHADOWDEPTHEXAGGERATION",
        "BASETEXTURETRANSFORM2",
        "LAYERTINT1",
        "LAYERTINT2",
        "BLENDMODULATETRANSFORM",
        "ENVMAPMASK2",
        "ENVMAPMASKTRANSFORM2",
        "NEWLAYERBLENDING",
        "BLENDSOFTNESS",
        "LAYERBORDERSTRENGTH",
        "LAYERBORDEROFFSET",
        "LAYERBORDERSOFTNESS",
        "LAYERBORDERTINT",
        "LAYEREDGENORMAL",
        "LAYEREDGEPUNCHIN",
        "LAYEREDGESTRENGTH",
        "LAYEREDGESOFTNESS",
        "LAYEREDGEOFFSET",
    },
}

matdyn.ShaderParams = {
    ['COLORTINT'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "Color tint",
        Multiple = true,
    },
    ['REFRACTAMOUNT'] = {
        Type = "number",
        DefaultValue = "2",
        Multiple = true,
    },
    ['NORMALMAP'] = {
        Type = "texture",
        DefaultValue = "models/shadertest/shader1_normal",
        Help = "normal map",
        Multiple = true,
    },
    ['BUMPFRAME'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "frame number for $bumpmap",
        Multiple = true,
    },
    ['BUMPTRANSFORM'] = {
        Type = "matrix",
        DefaultValue = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
        Help = "$bumpmap texcoord transform",
        Multiple = true,
    },
    ['SILHOUETTETHICKNESS'] = {
        Type = "number",
        DefaultValue = "1",
    },
    ['SILHOUETTECOLOR'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "Silhouette color tint",
    },
    ['GROUNDMIN'] = {
        Type = "number",
        DefaultValue = "1",
    },
    ['GROUNDMAX'] = {
        Type = "number",
        DefaultValue = "1",
    },
    ['BLURAMOUNT'] = {
        Type = "number",
        DefaultValue = "1",
        Multiple = true,
    },
    ['TIME'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "Needs CurrentTime Proxy",
        Multiple = true,
    },
    ['YTEXTURE'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "Y Bink Texture",
    },
    ['ATEXTURE'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "A Bink Texture",
    },
    ['CRTEXTURE'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "Cr Bink Texture",
    },
    ['CBTEXTURE'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "Cb Bink Texture",
    },
    ['BACKSURFACE'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "specify that this is the back surface of the blob",
        Multiple = true,
    },
    ['SPECMASKTEXTURE'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "specular reflection mask",
        Multiple = true,
    },
    ['LIGHTWARPTEXTURE'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "1D ramp texture for tinting scalar diffuse term",
        Multiple = true,
    },
    ['FRESNELWARPTEXTURE'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "1D ramp texture for controlling fresnel falloff",
        Multiple = true,
    },
    ['OPACITYTEXTURE'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "1D ramp texture for controlling fresnel falloff",
        Multiple = true,
    },
    ['UVSCALE'] = {
        Type = "number",
        DefaultValue = "0.02",
        Help = "uv projection scale",
        Multiple = true,
    },
    ['BUMPSTRENGTH'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "bump map strength",
        Multiple = true,
    },
    ['FRESNELBUMPSTRENGTH'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "bump map strength for fresnel",
        Multiple = true,
    },
    ['TRANSLUCENTFRESNELMINMAXEXP'] = {
        Type = "vector",
        DefaultValue = "[0.8 1.0 1.0]",
        Help = "fresnel params",
        Multiple = true,
    },
    ['INTERIOR'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Enable interior layer",
        Multiple = true,
    },
    ['INTERIORFOGSTRENGTH'] = {
        Type = "number",
        DefaultValue = "0.06",
        Help = "fog strength (scales with thickness of the interior volume)",
        Multiple = true,
    },
    ['INTERIORFOGLIMIT'] = {
        Type = "number",
        DefaultValue = "0.8",
        Help = "fog opacity beyond the range of destination alpha depth (in low-precision depth mode)",
        Multiple = true,
    },
    ['INTERIORFOGNORMALBOOST'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "degree to boost interior thickness/fog by 'side-on'ness of vertex normals to the camera",
        Multiple = true,
    },
    ['INTERIORBACKGROUNDBOOST'] = {
        Type = "number",
        DefaultValue = "7",
        Help = "boosts the brightness of bright background pixels",
        Multiple = true,
    },
    ['INTERIORAMBIENTSCALE'] = {
        Type = "number",
        DefaultValue = "0.3",
        Help = "scales ambient light in the interior volume",
        Multiple = true,
    },
    ['INTERIORBACKLIGHTSCALE'] = {
        Type = "number",
        DefaultValue = "0.3",
        Help = "scales backlighting in the interior volume",
        Multiple = true,
    },
    ['INTERIORCOLOR'] = {
        Type = "vector",
        DefaultValue = "[0.7 0.5 0.45]",
        Help = "tints light in the interior volume",
        Multiple = true,
    },
    ['INTERIORREFRACTSTRENGTH'] = {
        Type = "number",
        DefaultValue = "0.015",
        Help = "strength of bumped refract of the background seen through the interior",
        Multiple = true,
    },
    ['INTERIORREFRACTBLUR'] = {
        Type = "number",
        DefaultValue = "0.2",
        Help = "strength of blur applied to the background seen through the interior",
        Multiple = true,
    },
    ['DIFFUSEBOOST'] = {
        Type = "number",
        DefaultValue = "1.0",
    },
    ['PHONGEXPONENT'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "specular exponent",
        Multiple = true,
    },
    ['PHONGBOOST'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "specular boost",
        Multiple = true,
    },
    ['PHONGEXPONENT2'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "specular exponent",
        Multiple = true,
    },
    ['PHONGBOOST2'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "specular boost",
        Multiple = true,
    },
    ['RIMLIGHTEXPONENT'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "rim light exponent",
        Multiple = true,
    },
    ['RIMLIGHTBOOST'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "rim light boost",
        Multiple = true,
    },
    ['BASECOLORTINT'] = {
        Type = "vector",
        DefaultValue = "[1.0 1.0 1.0]",
        Help = "base texture tint",
        Multiple = true,
    },
    ['SELFILLUMFRESNEL'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "enable self illum fresnel term",
        Multiple = true,
    },
    ['SELFILLUMFRESNELMINMAXEXP'] = {
        Type = "vector",
        DefaultValue = "[0.7 0.5 0.45]",
        Help = "min max exponent",
        Multiple = true,
    },
    ['SELFILLUMTINT'] = {
        Type = "vector",
        DefaultValue = "[0.7 0.5 0.45]",
        Help = "selfillum color tint",
        Multiple = true,
    },
    ['UVPROJOFFSET'] = {
        Type = "vector",
        DefaultValue = "[0 0 0]",
        Help = "Center for UV projection",
        Multiple = true,
    },
    ['BBMIN'] = {
        Type = "vector",
        DefaultValue = "[0 0 0]",
        Multiple = true,
    },
    ['BBMAX'] = {
        Type = "vector",
        DefaultValue = "[0 0 0]",
        Multiple = true,
    },
    ['ARMATURE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "armature",
    },
    ['ARMCOLOR'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "arm color",
    },
    ['ARMWIDEN'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "widen arms at end instead of taper",
    },
    ['ARMWIDTHEXP'] = {
        Type = "number",
        DefaultValue = "1",
    },
    ['ARMWIDTHSCALE'] = {
        Type = "number",
        DefaultValue = "1",
    },
    ['ARMWIDTHBIAS'] = {
        Type = "number",
        DefaultValue = "0",
    },
    ['ANIMATEARMPULSES'] = {
        Type = "number",
        DefaultValue = "1",
    },
    ['GLOWSCALE'] = {
        Type = "number",
        DefaultValue = "4",
        Help = "Scale value applied to self-illum vertex colours",
    },
    ['PULSE'] = {
        Type = "number",
        DefaultValue = "1",
    },
    ['CONTACTSHADOWS'] = {
        Type = "number",
        DefaultValue = "1",
        Multiple = true,
    },
    ['VOLUMETEXTURETEST'] = {
        Type = "number",
        DefaultValue = "0",

    },
    ['RIMLIGHTALBEDO'] = {
        Type = "number",
        DefaultValue = "0.0",
    },
    ['SHADOWRIMBOOST'] = {
        Type = "number",
        DefaultValue = "2.0f",
        Help = "Extra boost for rim lights in shadow",
    },
    ['COLOR'] = {
        Type = "vector",
        DefaultValue = "{255 255 255}", 
        Help = "SHADER_PARAM_NOT_EDITABLE",
        Multiple = true,
    },
    ['SURFACEPROP'] = {
        Type = "string",
        DefaultValue = "", 
        Help = "https://developer.valvesoftware.com/wiki/Material_surface_properties",
        Multiple = true,
    },
    ['COLOR2'] = {
        Type = "vector",
        DefaultValue = "{255 255 255}",
        Multiple = true,
    },
    ['ALPHA'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "SHADER_PARAM_NOT_EDITABLE",
        Multiple = true,
    },
    ['REFRACTTINT'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "refraction tint",
        Multiple = true,
    },
    ['REFRACTTINTTEXTURE'] = {
        Type = "texture",
        DefaultValue = "models/shadertest/shield",
        Multiple = true,
    },
    ['REFRACTTINTTEXTUREFRAME'] = {
        Type = "number",
        DefaultValue = "0",
        Multiple = true,
    },
    ['FRESNELREFLECTION'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "1.0 == mirror, 0.0 == water",
        Multiple = true,
    },
    ['NOWRITEZ'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "0 == write z, 1 = no write z",
        Multiple = true,
    },
    ['MASKED'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "mask using dest alpha",
        Multiple = true,
    },
    ['CLOAKFACTOR'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "How cloaked?  Zero is not cloaked, 1 is fully cloaked.",
        Multiple = true,
    },
    ['PHONGTINT'] = {
        Type = "vector",
        DefaultValue = "5.0",
        Help = "Phong tint for local specular lights",
        Multiple = true,
    },
    ['PHONGALBEDOTINT'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "Apply tint by albedo (controlled by spec exponent texture",
        Multiple = true,
    },
    ['PHONGFRESNELRANGES'] = {
        Type = "vector",
        DefaultValue = "[0  0.5  1]",
        Help = "Parameters for remapping fresnel output",
        Multiple = true,
    },
    ['PHONGEXPONENTTEXTURE'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "Phong Exponent map",
        Multiple = true,
    },
    ['RIMLIGHT'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "enables rim lighting",
        Multiple = true,
    },
    ['RIMMASK'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Indicates whether or not to use alpha channel of exponent texture to mask the rim term",
        Multiple = true,
    },
    ['BASETEXTURE'] = {
        Type = "texture",
        DefaultValue = "shadertest/cloud", "cloud texture",
        Help = "0",
        Multiple = true,
    },
    ['CLOUDALPHATEXTURE'] = {
        Type = "texture",
        DefaultValue = "shadertest/cloudalpha",
        Help = "cloud alpha texture",
    },
    ['CLOUDSCALE'] = {
        Type = "vector",
        DefaultValue = "[1 1]",
        Help = "cloudscale",
    },
    ['MASKSCALE'] = {
        Type = "vector",
        DefaultValue = "[1 1]",
        Help = "maskscale",
    },
    ['DUMMYPARAM'] = {
        Type = "vector",
        DefaultValue = "[0 0 0]",
    },
    ['SURFACETEXTURE'] = {
        Type = "texture",
        DefaultValue = "shader/SurfaceTexture",
        Help = "RGB: Object-space normal, A: Cavity",
    },
    ['AOTEXTURE'] = {
        Type = "texture",
        DefaultValue = "shader/AOTexture",
        Help = "RGB: Ambient Occlusion",
        Multiple = true,
    },
    ['MASKSTEXTURE'] = {
        Type = "texture",
        DefaultValue = "shader/MasksTexture",
        Help = "R: Anodized, G: Camo2, B: Camo3, A: Black is paintable, White reveals original basetexture",
    },
    ['POSTEXTURE'] = {
        Type = "texture",
        DefaultValue = "shader/PosTexture",
        Help = "RGB: High-precision object-space position",
    },
    ['GRUNGETEXTURE'] = {
        Type = "texture",
        DefaultValue = "shader/PosTexture",
        Help = "RGB: Tiling grunge A: spec, black dulls the paint finish",
        Multiple = true,
    },
    ['WEARTEXTURE'] = {
        Type = "texture",
        DefaultValue = "shader/PosTexture",
        Help = "RGB: Greyscale wear speed factor, white wears soonest",
        Multiple = true,
    },
    ['PAINTTEXTURE'] = {
        Type = "texture",
        DefaultValue = "shader/PosTexture",
        Help = "RGB: High-precision object-space position",
    },
    ['EXPTEXTURE'] = {
        Type = "texture",
        DefaultValue = "shader/PosTexture",
        Help = "RGB: Exponent texture",
        Multiple = true,
    },
    ['CAMOCOLOR0'] = {
        Type = "vector",
        DefaultValue = "[ 0 0 0 ]",
        Help = "Customization color 0",
    },
    ['CAMOCOLOR1'] = {
        Type = "vector",
        DefaultValue = "[ 0 0 0 ]",
        Help = "Customization color 1",
    },
    ['CAMOCOLOR2'] = {
        Type = "vector",
        DefaultValue = "[ 0 0 0 ]",
        Help = "Customization color 2",
    },
    ['CAMOCOLOR3'] = {
        Type = "vector",
        DefaultValue = "[ 0 0 0 ]",
        Help = "Customization color 3",
    },
    ['BASEDIFFUSEOVERRIDE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Set if this customization style needs a different (non-default) underlying diffuse map for this weapon",
    },
    ['WEARPROGRESS'] = {
        Type = "number",
        DefaultValue = "0.45",
        Help = "Wear/worn progress amount",
        Multiple = true,
    },
    ['PHONGALBEDOBOOST'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Phong albedo boost value for anodized metallic effect",
        Multiple = true,
    },
    ['PHONGINTENSITY'] = {
        Type = "number",
        DefaultValue = "10",
        Help = "Phong intensity value",
    },
    ['PAINTSTYLE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Indicates a specific customization style: 0 = none, 1 = solid, 2 = hydrographic, 3 = spray, 4 = anodized, 5 = anodized multicolored, 6 = anodized airbrushed, 7 = custom texture, 8 = patina/antiqued",
    },
    ['EXPONENTMODE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Set to 1 to an exponent texture for the given style rather than a base diffuse",
    },
    ['PATTERNTEXTURETRANSFORM'] = {
        Type = "matrix",
        DefaultValue = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
        Help = "$PAINTTEXTURE texcoord transform",
        Multiple = true,
    },
    ['WEARTEXTURETRANSFORM'] = {
        Type = "matrix",
        DefaultValue = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
        Help = "$WEARTEXTURE texcoord transform",
    },
    ['GRUNGETEXTURETRANSFORM'] = {
        Type = "matrix",
        DefaultValue = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
        Help = "$GRUNGETEXTURE texcoord transform",
    },
    ['PHONGALBEDOFACTOR'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "When using the anodizing mode, some specular values already affected by phongalbedo in the source need to be reduced to compensate for increase in phongalbedoboost",
    },
    ['PREVIEW'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Enable to preview the shader, realtime, on a model",
    },
    ['PAINTPHONGALBEDOBOOST'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "Phong albedo boost for preview render",
    },
    ['PREVIEWWEAPONOBJSCALE'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "Weapon-specific scale factor for patterns applied via object space projections",
    },
    ['PREVIEWWEAPONUVSCALE'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "Weapon-specific scale factor for patterns applied via UVs",
    },
    ['PREVIEWIGNOREWEAPONSCALE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Paint-specific toggle for ignoring weapon-specific scales",
    },
    ['SHOWALPHA'] = {
        Type = "number",
        DefaultValue = "0",
    },
    ['NCOLORS'] = {
        Type = "number",
        DefaultValue = "10",
        Help = "Number of colors for posterization",
    },
    ['COLORGAMMA'] = {
        Type = "number",
        DefaultValue = "0.8",
        Help = "Gamma for posterization",
    },
    ['TEXTUREMODE'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Multiple textures need to be generated for end-use render. Mode determines which one we're working on.",
    },
    ['BASETEXTURETRANSFORM'] = {
        Type = "matrix",
        DefaultValue = "center .5 .5 scale 1 1 rotate 0 translate 0 0", 
        Help = "SHADER_PARAM_NOT_EDITABLE",
    },
    ['IRIS'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "iris texture",
        Multiple = true,
    },
    ['IRISFRAME'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "frame for the iris texture",
        Multiple = true,
    },
    ['GLINT'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "glint texture",
    },
    ['EYEORIGIN'] = {
        Type = "vector",
        DefaultValue = "[0 0 0]",
        Help = "origin for the eyes",
        Multiple = true,
    },
    ['EYEUP'] = {
        Type = "vector",
        DefaultValue = "[0 0 1]",
        Help = "up vector for the eyes",
    },
    ['IRISU'] = {
        Type = "color",
        DefaultValue = "[0 1 0 0 ]",
        Help = "U projection vector for the iris",
        Multiple = true,
    },
    ['IRISV'] = {
        Type = "color",
        DefaultValue = "[0 0 1 0]",
        Help = "V projection vector for the iris",
        Multiple = true,
    },
    ['GLINTU'] = {
        Type = "color",
        DefaultValue = "[0 1 0 0]",
        Help = "U projection vector for the glint",

    },
    ['GLINTV'] = {
        Type = "color",
        DefaultValue = "[0 0 1 0]",
        Help = "V projection vector for the glint",
    },
    ['DILATION'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Pupil dilation (0 is none, 1 is maximal)",
        Multiple = true,
    },
    ['CORNEATEXTURE'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "cornea texture",
    },
    ['AMBIENTOCCLTEXTURE'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "reflection texture",
    },
    ['ENVMAP'] = {
        Type = "texture",
        DefaultValue = "shadertest/shadertest_env",
        Help = "envmap",
        Multiple = true,
    },
    ['GLOSSINESS'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Glossiness of eye (1 is default, 0 is not glossy at all)",
    },
    ['SPHERETEXKILLCOMBO'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "texkill pixels not on sphere",
    },
    ['RAYTRACESPHERE'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Raytrace sphere",
    },
    ['PARALLAXSTRENGTH'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Parallax strength",
    },
    ['CORNEABUMPSTRENGTH'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Cornea strength",
    },
    ['AMBIENTOCCLCOLOR'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "Ambient occlusion color",
    },
    ['AMBIENTOCCLUSION'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "Dynamic ambient occlusion strength",
        Multiple = true,
    },
    ['EYEBALLRADIUS'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Eyeball radius for ray casting",
    },
    ['CLOAKPASSENABLED'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Enables cloak render in a second pass",
        Multiple = true,
    },
    ['CLOAKCOLORTINT'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "Cloak color tint",
        Multiple = true,
    },
    ['EMISSIVEBLENDENABLED'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Enable emissive blend pass",
        Multiple = true,
    },
    ['EMISSIVEBLENDSCROLLVECTOR'] = {
        Type = "vector",
        DefaultValue = "[0.11 0.124]",
        Help = "Emissive scroll vec",
        Multiple = true,
    },
    ['EMISSIVEBLENDSTRENGTH'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "Emissive blend strength",
        Multiple = true,
    },
    ['EMISSIVEBLENDTINT'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "Self-illumination tint",
        Multiple = true,
    },
    ['SHARPNESS'] = {
        Type = "number",
        DefaultValue = "1",
    },
    ['WOODCUT'] = {
        Type = "number",
        DefaultValue = "0",
    },
    ['BLOOMAMOUNT'] = {
        Type = "number",
        DefaultValue = "1.0",
    },
    ['BLOOMEXPONENT'] = {
        Type = "number",
        DefaultValue = "2.0",
    },
    ['ALPHASHARPENFACTOR'] = {
        Type = "number",
        DefaultValue = "0.0",
    },
    ['AUTOEXPOSE_MIN'] = {
        Type = "number",
        DefaultValue = ".5",
    },
    ['AUTOEXPOSE_MAX'] = {
        Type = "number",
        DefaultValue = "2",
    },
    ['DIFFUSESCALE'] = {
        Type = "number",
        DefaultValue = "1.0",
        Multiple = true,
    },
    ['ENVMAPTINT'] = {
        Type = "vector",
        DefaultValue = "[1.0 1.0 1.0]",
        Help = "tints the environment reflection",
        Multiple = true,
    },
    ['REFRACTTEXTURE'] = {
        Type = "texture",
        DefaultValue = "_rt_WaterRefraction",
    },
    ['REFLECTTEXTURE'] = {
        Type = "texture",
        DefaultValue = "_rt_WaterReflection",
    },
    ['REFLECTAMOUNT'] = {
        Type = "number",
        DefaultValue = "0.8",
    },
    ['REFLECTTINT'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "reflection tint",
    },
    ['ENVMAPMASK'] = {
        Type = "texture",
        DefaultValue = "shadertest/shadertest_envmask",
        Help = "envmap mask",
        Multiple = true,
    },
    ['REFLECTANCE'] = {
        Type = "number",
        DefaultValue = "0.25",
    },
    ['WORLDTOTEXTURE'] = {
        Type = "matrix",
        DefaultValue = "1",
        Help = "World to Texture Matrix",
    },
    ['FLASHLIGHTCOLOR'] = {
        Type = "color",
        DefaultValue = "1",
        Help = "Flashlight color",
    },
    ['ATTENFACTORS'] = {
        Type = "color",
        DefaultValue = "1",
        Help = "Packed attenuation factors",
    },
    ['ORIGINFARZ'] = {
        Type = "color",
        DefaultValue = "1",
        Help = "Light origin packed with farz",
    },
    ['QUATORIENTATION'] = {
        Type = "color",
        DefaultValue = "1",
        Help = "Light orientation (quaternion)",
    },
    ['SHADOWFILTERSIZE'] = {
        Type = "number",
        DefaultValue = "3",
        Help = "Shadow filter size",
    },
    ['SHADOWATTEN'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Shadow Attenuation",
    },
    ['SHADOWJITTERSEED'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Shadow jitter seed",
    },
    ['UBERLIGHT'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Is this an uberlight?",
    },
    ['ENABLESHADOWS'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Are shadows enabled?",
    },
    ['NOISESTRENGTH'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Strength of noise in volumetrics",
    },
    ['UBERNEARFAR'] = {
        Type = "color",
        DefaultValue = "1",
        Help = "Packed uberlight near and far parameters",
    },
    ['UBERHEIGHTWIDTH'] = {
        Type = "color",
        DefaultValue = "1",
        Help = "Packed uberlight height and width parameters",
    },
    ['UBERROUNDNESS'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Uberlight roundness",
    },
    ['FLASHLIGHTTIME'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Typically driven by SFM, similar to jitter seed",
    },
    ['NUMPLANES'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Need to know this to normalize intensity",
    },
    ['VOLUMETRICINTENSITY'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Intensity of volumetrics",
    },
    ['ROTATION'] = {
        Type = "number",
        DefaultValue = "0.0",
    },
    ['SCALE'] = {
        Type = "number",
        DefaultValue = "1.0",
    },
    ['ROTATION2'] = {
        Type = "number",
        DefaultValue = "0.0",
    },
    ['SCALE2'] = {
        Type = "number",
        DefaultValue = "1.0",
    },
    ['ROTATION3'] = {
        Type = "number",
        DefaultValue = "0.0",
    },
    ['SCALE3'] = {
        Type = "number",
        DefaultValue = "1.0",
    },
    ['ROTATION4'] = {
        Type = "number",
        DefaultValue = "0.0",
    },
    ['SCALE4'] = {
        Type = "number",
        DefaultValue = "1.0",
    },
    ['STAGE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Stage of portal rendering (0, 1, 2)",
    },
    ['PORTALOPENAMOUNT'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "Portal open amount 0.0-1.0",
    },
    ['PORTALSTATIC'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "Portal static amount 0.0-1.0",
    },
    ['TEXTURETRANSFORM'] = {
        Type = "matrix",
        DefaultValue = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
        Help = "Texcoord transform",
    },
    ['PORTALCOLORGRADIENTDARK'] = {
        Type = "vector",
        DefaultValue = "[0.0 0.0 0.0]",
        Help = "The dark end of a tint gradient if not using a color texture",
    },
    ['PORTALCOLORGRADIENTLIGHT'] = {
        Type = "vector",
        DefaultValue = "[1.0 1.0 1.0]",
        Help = "The light end of a tint gradient if not using a color texture",
    },
    ['PORTALCOLORSCALE'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "Portal color scale",
    },
    ['USEONSTATICPROP'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Activate special mode to use this shader on a static prop",
    },
    ['SSBUMP'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "whether or not to use alternate bumpmap format with height",
        Multiple = true,
    },
    ['NORMALMAP2'] = {
        Type = "texture",
        DefaultValue = "models/shadertest/shader1_normal",
        Help = "normal map",
    },
    ['BUMPFRAME2'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "frame number for $normalmap",
        Multiple = true,
    },
    ['BUMPTRANSFORM2'] = {
        Type = "matrix",
        DefaultValue = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
        Help = "$normalmap texcoord transform",
        Multiple = true,
    },
    ['FADEOUTONSILHOUETTE'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "0 for no fade out on silhouette, 1 for fade out on sillhouette",
    },
    ['ENVMAPFRAME'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "envmap frame number",
        Multiple = true,
    },
    ['ENVMAPCONTRAST'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "contrast 0 == normal 1 == color*color",
        Multiple = true,
    },
    ['ENVMAPSATURATION'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "saturation 0 == greyscale 1 == normal",
        Multiple = true,
    },
    ['NOVIEWPORTFIXUP'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Don't adjust uv's for current viewport",
    },
    ['MIRRORABOUTVIEWPORTEDGES'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "don't sample outside of the viewport",
    },
    ['MAGNIFYENABLE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Enable magnification of refracted image around the $magnifyCenter screen position by $magnifyScale",
    },
    ['MAGNIFYCENTER'] = {
        Type = "vector",
        DefaultValue = "[0 0]",
        Help = "Magnify refracted image around this screen position",
    },
    ['MAGNIFYSCALE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Magnify refracted image by this factor",
    },
    ['LOCALREFRACT'] = {
        Type = "number",
        DefaultValue = "0",
    },
    ['LOCALREFRACTDEPTH'] = {
        Type = "number",
        DefaultValue = "0",
    },
    ['PIXSHADER'] = {
        Type = "string",
        DefaultValue = "sample4x4_ps20",
        Help = "Name of the pixel shader to use",
    },
    ['DETAIL1'] = {
        Type = "texture",
        DefaultValue = "shader/BaseTexture",
        Help = "detail map 1",
    },
    ['DETAIL1SCALE'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "scale detail1 as multiplier of base UVs",
    },
    ['DETAIL1FRAME'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "frame number for detail1",
    },
    ['DETAIL1BLENDMODE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "detail 1 blend mode: 0=add, 1=mod2x, 2=mul, 3=alphamul (mul masked by base alpha)",
    },
    ['DETAIL1BLENDFACTOR'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "detail 1 blend factor",
    },
    ['DETAIL1TEXTURETRANSFORM'] = {
        Type = "matrix",
        DefaultValue = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
        Help = "detail1 texcoord transform",
    },
    ['DETAIL2'] = {
        Type = "texture",
        DefaultValue = "shader/BaseTexture",
        Help = "detail map 2",
        Multiple = true,
    },
    ['DETAIL2SCALE'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "scale detail1 as multiplier of base UVs",
    },
    ['DETAIL2FRAME'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "frame number for detail1",
    },
    ['DETAIL2BLENDMODE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "detail 1 blend mode: 0=add, 1=mod2x, 2=mul, 3=detailmul (mul with detail1)",
    },
    ['DETAIL2BLENDFACTOR'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "detail 1 blend factor",
    },
    ['DETAIL2TEXTURETRANSFORM'] = {
        Type = "matrix",
        DefaultValue = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
        Help = "detail1 texcoord transform",
    },
    ['TANGENTTOPACITYRANGES'] = {
        Type = "color",
        DefaultValue = "[1 0.9 0 0.6]",
        Help = "enables view-based opacity falloff based on tangent t direction, great for cylinders, includes last term for scaling backface opacity",
    },
    ['TANGENTSOPACITYRANGES'] = {
        Type = "color",
        DefaultValue = "[1 0.9 0 0.6]",
        Help = "enables view-based opacity falloff based on tangent s direction, great for cylinders, includes last term for scaling backface opacity",
    },
    ['FRESNELOPACITYRANGES'] = {
        Type = "color",
        DefaultValue = "[1 0.9 0 0.6]",
        Help = "enables fresnel-based opacity falloff, includes last term for scaling backface opacity",
    },
    ['NEEDSTANGENTT'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "don't need to set this explicitly, it gets set when tangenttopacityranges is defined",
    },
    ['NEEDSTANGENTS'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "don't need to set this explicitly, it gets set when tangentSopacityranges is defined",
    },
    ['NEEDSNORMALS'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "don't need to set this explicitly, it gets set when fresnelopacityranges is defined",
    },
    ['DEPTHBLEND'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "enables depth-feathering",
    },
    ['DEPTHBLENDSCALE'] = {
        Type = "number",
        DefaultValue = "50.0",
        Help = "Amplify or reduce DEPTHBLEND fading. Lower values make harder edges.",
    },
    ['FLOWMAPFRAME'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "frame number for $flowmap",
    },
    ['FLOWMAPSCROLLRATE'] = {
        Type = "vector",
        DefaultValue = "[0 0",
        Help = "2D rate to scroll $flowmap",
    },
    ['OUTPUTINTENSITY'] = {
        Type = "number",
        DefaultValue = "1.0",
    },
    ['SHADERSRGBREAD360'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Simulate srgb read in shader code",
        Multiple = true,
    },
    ['SHADOWDEPTH'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "writing to a shadow depth buffer",
    },
    ['BUMPMAP'] = {
        Type = "texture",
        DefaultValue = "cable/cablenormalmap",
        Help = "normal map",
        Multiple = true,
    },
    ['TILING'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "cable texture tiling multiplier",
    },
    ['ALPHATESTREFERENCE'] = {
        Type = "number",
        DefaultValue = "1",
        Multiple = true,
    },
    ['ILLUMFACTOR'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Amount to darken or brighten the teeth",
    },
    ['FORWARD'] = {
        Type = "vector",
        DefaultValue = "[1 0 0]",
        Help = "Forward direction vector for teeth lighting",
    },
    ['ALBEDO'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "albedo (Base texture with no baked lighting)",
        Multiple = true,
    },
    ['DETAIL'] = {
        Type = "texture",
        DefaultValue = "shadertest/detail",
        Help = "detail texture",
        Multiple = true,
    },
    ['DETAILFRAME'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "frame number for $detail",
        Multiple = true,
    },
    ['DETAILSCALE'] = {
        Type = "number",
        DefaultValue = "4",
        Help = "scale of the detail texture",
        Multiple = true,
    },
    ['ENVMAPMASKFRAME'] = {
        Type = "number",
        DefaultValue = "0",
        Multiple = true,
    },
    ['ENVMAPMASKTRANSFORM'] = {
        Type = "matrix",
        DefaultValue = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
        Help = "$envmapmask texcoord transform",
        Multiple = true,
    },
    ['VERTEXALPHATEST'] = {
        Type = "number",
        DefaultValue = "0",
    },
    ['HDRCOLORSCALE'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "hdr color scale",
    },
    ['PHONGWARPTEXTURE'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "2D map for warping specular",
        Multiple = true,
    },
    ['PHONG'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "enables phong lighting",
        Multiple = true,
    },
    ['DETAILBLENDMODE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "mode for combining detail texture with base. 0=normal, 1= additive, 2=alpha blend detail over base, 3=crossfade",
        Multiple = true,
    },
    ['DETAILBLENDFACTOR'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "blend amount for detail texture.",
        Multiple = true,
    },
    ['DETAILTEXTURETRANSFORM'] = {
        Type = "matrix",
        DefaultValue = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
        Help = "$detail texcoord transform",
        Multiple = true,
    },
    ['DECALBLENDMODE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "mode for combining decal texture with base. 0=normal(decal*srca + base*(1-srca), 1= mod, 2=mod2x, 3=additive",
        Multiple = true,
    },
    ['DISTANCEALPHA'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Use distance-coded alpha generated from hi-res texture by vtex.",
    },
    ['DISTANCEALPHAFROMDETAIL'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Take the distance-coded alpha mask from the detail texture.",
    },
    ['SOFTEDGES'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Enable soft edges to distance coded textures.",
    },
    ['SCALEEDGESOFTNESSBASEDONSCREENRES'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Scale the size of the soft edges based upon resolution. 1024x768 = nominal.",
    },
    ['EDGESOFTNESSSTART'] = {
        Type = "number",
        DefaultValue = "0.6",
        Help = "Start value for soft edges for distancealpha.",
    },
    ['EDGESOFTNESSEND'] = {
        Type = "number",
        DefaultValue = "0.5",
        Help = "End value for soft edges for distancealpha.",
    },
    ['GLOW'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Enable glow/shadow for distance coded textures.",
    },
    ['GLOWCOLOR'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "color of outter glow for distance coded line art.",
    },
    ['GLOWALPHA'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Base glow alpha amount for glows/shadows with distance alpha.",
    },
    ['GLOWSTART'] = {
        Type = "number",
        DefaultValue = "0.7",
        Help = "start value for glow/shadow",
    },
    ['GLOWEND'] = {
        Type = "number",
        DefaultValue = "0.5",
        Help = "end value for glow/shadow",
    },
    ['GLOWX'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "texture offset x for glow mask.",
    },
    ['GLOWY'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "texture offset y for glow mask.",
    },
    ['OUTLINE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Enable outline for distance coded textures.",
    },
    ['OUTLINECOLOR'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "color of outline for distance coded images.",
    },
    ['OUTLINEALPHA'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "alpha value for outline",
    },
    ['OUTLINESTART0'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "outer start value for outline",
    },
    ['OUTLINESTART1'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "inner start value for outline",
    },
    ['OUTLINEEND0'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "inner end value for outline",
    },
    ['OUTLINEEND1'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "outer end value for outline",
    },
    ['SCALEOUTLINESOFTNESSBASEDONSCREENRES'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Scale the size of the soft part of the outline based upon resolution. 1024x768 = nominal.",
    },
    ['SEPARATEDETAILUVS'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Use texcoord1 for detail texture",
        Multiple = true,
    },
    ['GAMMACOLORREAD'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Disables SRGB conversion of color texture read.",
    },
    ['LINEARWRITE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Disables SRGB conversion of shader results.",
        Multiple = true,
    },
    ['RECEIVEFLASHLIGHT'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Forces this material to receive flashlights.",
    },
    ['SINGLEPASSFLASHLIGHT'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Flags this material as possibly being run through single pass flashlight code",
    },
    ['DISPLACEMENTMAP'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "Displacement map",
        Multiple = true,
    },
    ['TEXTURE2'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "second texture",
    },
    ['FRAME2'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "frame number for $texture2",
        Multiple = true,
    },
    ['TEXTURE2TRANSFORM'] = {
        Type = "matrix",
        DefaultValue = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
        Help = "$texture2 texcoord transform",
    },
    ['CROSSHAIRMODE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Crosshair mode",
    },
    ['CROSSHAIRCOLORTINT'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
    },
    ['CROSSHAIRCOLORADAPT'] = {
        Type = "number",
        DefaultValue = "0.4",
    },
    ['COMPRESS'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "compression wrinklemap",
    },
    ['STRETCH'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "expansion wrinklemap",
    },
    ['BUMPCOMPRESS'] = {
        Type = "texture",
        DefaultValue = "models/shadertest/shader3_normal",
        Help = "compression bump map",
    },
    ['BUMPSTRETCH'] = {
        Type = "texture",
        DefaultValue = "models/shadertest/shader1_normal",
        Help = "expansion bump map",
    },
    ['SELFILLUMMASKSCALE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Scale self illum effect strength",
    },
    ['SELFILLUMFRESNELENABLEDTHISFRAME'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Self illum fresnel",
    },
    ['ALLOWFENCERENDERSTATEHACK'] = {
        Type = "number",
        DefaultValue = "0",
    },
    ['FLASHLIGHTNOLAMBERT'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Flashlight pass sets N.L=1.0",
    },
    ['LOWQUALITYFLASHLIGHTSHADOWS'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Force low quality flashlight shadows (faster)",
    },
    ['DISABLECSMLOOKUP'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Force no CSM lookup/filter (faster)",
    },
    ['AMBIENTONLY'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Control drawing of non-ambient light ()",
    },
    ['FORCEPHONG'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "forces Phong lighting, even at low GPU levels (Phong must already be enabled)",
    },
    ['BASEMAPALPHAPHONGMASK'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "indicates that there is no normal map and that the phong mask is in base alpha",
    },
    ['INVERTPHONGMASK'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "invert the phong mask (0=full phong, 1=no phong)",
    },
    ['ENVMAPFRESNEL'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Degree to which Fresnel should be applied to env map",
    },
    ['SELFILLUMMASK'] = {
        Type = "texture",
        DefaultValue = "shadertest/BaseTexture",
        Help = "If we bind a texture here, it overrides base alpha (if any) for self illum",
    },
    ['BASEMAPLUMINANCEPHONGMASK'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "indicates that the base luminance should be used to mask phong",
    },
    ['DETAILTINT'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "detail texture tint",
        Multiple = true,
    },
    ['SEAMLESS_BASE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "whether to apply seamless mapping to the base texture. requires a smooth model.",
    },
    ['SEAMLESS_DETAIL'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "where to apply seamless mapping to the detail texture.",
    },
    ['SEAMLESS_SCALE'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "the scale for the seamless mapping. # of repetions of texture per inch.",
        Multiple = true,
    },
    ['FLESHINTERIORENABLED'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Enable Flesh interior blend pass",
    },
    ['FLESHBORDERNOISESCALE'] = {
        Type = "number",
        DefaultValue = "1.5",
        Help = "Flesh Noise UV scalar for border",
    },
    ['FLESHDEBUGFORCEFLESHON'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Flesh Debug full flesh",
    },
    ['FLESHEFFECTCENTERRADIUS1'] = {
        Type = "color",
        DefaultValue = "[0 0 0 0.001]",
        Help = "Flesh effect center and radius",
    },
    ['FLESHEFFECTCENTERRADIUS2'] = {
        Type = "color",
        DefaultValue = "[0 0 0 0.001]",
        Help = "Flesh effect center and radius",
    },
    ['FLESHEFFECTCENTERRADIUS3'] = {
        Type = "color",
        DefaultValue = "[0 0 0 0.001]",
        Help = "Flesh effect center and radius",
    },
    ['FLESHEFFECTCENTERRADIUS4'] = {
        Type = "color",
        DefaultValue = "[0 0 0 0.001]",
        Help = "Flesh effect center and radius",
    },
    ['FLESHSUBSURFACETINT'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "Subsurface Color",
    },
    ['FLESHBORDERWIDTH'] = {
        Type = "number",
        DefaultValue = "0.3",
        Help = "Flesh border",
    },
    ['FLESHBORDERSOFTNESS'] = {
        Type = "number",
        DefaultValue = "0.42",
        Help = "Flesh border softness (> 0.0 && <= 0.5)",
    },
    ['FLESHBORDERTINT'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "Flesh border Color",
    },
    ['FLESHGLOBALOPACITY'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "Flesh global opacity",
    },
    ['FLESHGLOSSBRIGHTNESS'] = {
        Type = "number",
        DefaultValue = "0.66",
        Help = "Flesh gloss brightness",
    },
    ['FLESHSCROLLSPEED'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "Flesh scroll speed",
    },
    ['DISPLACEMENTWRINKLE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Displacement map contains wrinkle displacements",
    },
    ['BLENDTINTBYBASEALPHA'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Use the base alpha to blend in the $color modulation",
    },
    ['NOTINT'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Disable tinting",
    },
    ['DESATURATEWITHBASEALPHA'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "Use the base alpha to desaturate the base texture.  Set to non-zero to enable, value gets multiplied into the alpha channel before desaturating.",
    },
    ['ALLOWDIFFUSEMODULATION'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "Allow per-instance color modulation",
    },
    ['ENVMAPFRESNELMINMAXEXP'] = {
        Type = "vector",
        DefaultValue = "[0.0 1.0 2.0]",
        Help = "Min/max fresnel range and exponent for vertexlitgeneric",
    },
    ['BASEALPHAENVMAPMASKMINMAXEXP'] = {
        Type = "vector",
        DefaultValue = "[1.0 0.0 1.0]",
    },
    ['PHONGDISABLEHALFLAMBERT'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Disable half lambert for phong",
    },
    ['TREESWAY'] = {
        Type = "number",
        DefaultValue = "0",
    },
    ['TREESWAYHEIGHT'] = {
        Type = "number",
        DefaultValue = "1000",
    },
    ['TREESWAYSTARTHEIGHT'] = {
        Type = "number",
        DefaultValue = "0.2",
    },
    ['TREESWAYRADIUS'] = {
        Type = "number",
        DefaultValue = "300",
    },
    ['TREESWAYSTARTRADIUS'] = {
        Type = "number",
        DefaultValue = "0.1",
    },
    ['TREESWAYSPEED'] = {
        Type = "number",
        DefaultValue = "1",
    },
    ['TREESWAYSPEEDHIGHWINDMULTIPLIER'] = {
        Type = "number",
        DefaultValue = "2",
    },
    ['TREESWAYSTRENGTH'] = {
        Type = "number",
        DefaultValue = "10",
    },
    ['TREESWAYSCRUMBLESPEED'] = {
        Type = "number",
        DefaultValue = "0.1",
    },
    ['TREESWAYSCRUMBLESTRENGTH'] = {
        Type = "number",
        DefaultValue = "0.1",
    },
    ['TREESWAYSCRUMBLEFREQUENCY'] = {
        Type = "number",
        DefaultValue = "0.1",
    },
    ['TREESWAYFALLOFFEXP'] = {
        Type = "number",
        DefaultValue = "1.5",
    },
    ['TREESWAYSCRUMBLEFALLOFFEXP'] = {
        Type = "number",
        DefaultValue = "1.0",
    },
    ['TREESWAYSPEEDLERPSTART'] = {
        Type = "number",
        DefaultValue = "3",
    },
    ['TREESWAYSPEEDLERPEND'] = {
        Type = "number",
        DefaultValue = "6",
    },
    ['TREESWAYSTATIC'] = {
        Type = "number",
        DefaultValue = "0",
    },
    ['ENVMAPLIGHTSCALE'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "How much the lightmap effects environment map reflection, 0.0 is off, 1.0 will allow complete blackness of the environment map if the lightmap is black",
        Multiple = true,
    },
    ['ENVMAPLIGHTSCALEMINMAX'] = {
        Type = "vector",
        DefaultValue = "[0.0 1.0]",
        Help = "Thresholds for the lightmap envmap effect.  Setting the min higher increases the minimum light amount at which the envmap gets nerfed to nothing.",
        Multiple = true,
    },
    ['BLENDWITHSMOKEGRENADE'] = {
        Type = "number",
        DefaultValue = "0",
    },
    ['BLENDWITHSMOKEGRENADEPOSENTITY'] = {
        Type = "vector",
        DefaultValue = "[0 0 0]",
    },
    ['BLENDWITHSMOKEGRENADEPOSSMOKE'] = {
        Type = "vector",
        DefaultValue = "[0 0 0]",
    },
    ['MODELDECALIGNOREZ'] = {
        Type = "number",
        DefaultValue = "0",
    },
    ['ENVMAPMASKINTINTMASKTEXTURE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Envmap mask is stored in ting mask texture (instead of normal map alpha)",
    },
    ['THIRDPERSON'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Third-person mode",
    },
    ['ANISODIRTEXTURE'] = {
        Type = "texture",
        DefaultValue = "black",
        Help = "RG give direction vector, A masks specularity",
    },
    ['MIRRORHORIZONTAL'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Flip decal horizontally",
    },
    ['WEARREMAPMIN'] = {
        Type = "number",
        DefaultValue = "0.0",
    },
    ['WEARREMAPMID'] = {
        Type = "number",
        DefaultValue = "0.5",
    },
    ['WEARREMAPMAX'] = {
        Type = "number",
        DefaultValue = "1.0",
    },
    ['WEARWIDTHMIN'] = {
        Type = "number",
        DefaultValue = "0.3",
    },
    ['WEARWIDTHMAX'] = {
        Type = "number",
        DefaultValue = "0.06",
    },
    ['ALPHAMASK'] = {
        Type = "number",
        DefaultValue = "0",
    },
    ['FASTWEARTHRESHOLD'] = {
        Type = "number",
        DefaultValue = "0.0",
    },
    ['HIGHLIGHT'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "Highlight the edges of the sticker",
    },
    ['HIGHLIGHTCYCLE'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "Scroll the highlight effect",
    },
    ['PEEL'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "An effect that 'peels' the sticker in local uv space",
    },
    ['DECALSTYLE'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Decal style: 0 = Plastic/PVC sticker",
    },
    ['PATTERNROTATION'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "Pattern rotation",
    },
    ['PATTERNSCALE'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "Pattern scale",
    },
    ['COLORTINT4'] = {
        Type = "vector",
        DefaultValue = "[ 1 1 1 ]",
        Help = "Diffuse tint",
    },
    ['COLORTINT3'] = {
        Type = "vector",
        DefaultValue = "[ 1 1 1 ]",
        Help = "Diffuse tint",
    },
    ['COLORTINT2'] = {
        Type = "vector",
        DefaultValue = "[ 1 1 1 ]",
        Help = "Diffuse tint",
    },
    ['WEARBIAS'] = {
        Type = "number",
        DefaultValue = "0.5",
    },
    ['UNWEARSTRENGTH'] = {
        Type = "number",
        DefaultValue = "0.1",
    },
    ['GRUNGESCALE'] = {
        Type = "number",
        DefaultValue = "2",
    },
    ['DESATBASETINT'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Desaturate basemap and affect tint",
    },
    ['DETAILFRAME2'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "frame number for $detail2",
    },
    ['DETAILSCALE2'] = {
        Type = "number",
        DefaultValue = "4",
        Help = "scale of the detail texture 2",
    },
    ['DETAILBLENDFACTOR2'] = {
        Type = "number",
        DefaultValue = "1",
        Help = "blend amount for detail texture 2.",
    },
    ['DETAILTINT2'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "detail texture 2 tint",
    },
    ['NODIFFUSEBUMPLIGHTING'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "0 == Use diffuse bump lighting, 1 = No diffuse bump lighting",
    },
    ['BUMPMAP2'] = {
        Type = "texture",
        DefaultValue = "models/shadertest/shader3_normal",
        Help = "bump map",
    },
    ['BUMPMASK'] = {
        Type = "texture",
        DefaultValue = "models/shadertest/shader1_normal",
        Help = "bump map",
    },
    ['BASETEXTURE2'] = {
        Type = "texture",
        DefaultValue = "shadertest/detail",
        Help = "detail texture",
    },
    ['BUMP_FORCE_ON'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "force bump-mapping on, even for low-end machines",
    },
    ['ENVMAPANISOTROPY'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Enable anisotropic cubemap lookups for macroscopically rough/microscopically smooth surfaces, like wet asphalt",
    },
    ['ENVMAPANISOTROPYSCALE'] = {
        Type = "number",
        DefaultValue = "1.0",
        Help = "Scale anisotropy amount for cubemap lookups",
    },
    ['PHONGBASETINT'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "Amount to tint Phong * $basetexture",

    },
    ['PHONGBASETINT2'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "Amount to tint Phong * $basetexture2",
    },
    ['PHONGMASKCONTRASTBRIGHTNESS'] = {
        Type = "vector",
        DefaultValue = "[1.0 0.0]",
        Help = "Contrast and Brightness for Phong Mask generation using $basetexture",
    },
    ['PHONGMASKCONTRASTBRIGHTNESS2'] = {
        Type = "vector",
        DefaultValue = "[1.0 0.0]",
        Help = "Contrast and Brightness for Phong Mask generation using $basetexture2",
    },
    ['PHONGAMOUNT'] = {
        Type = "color",
        DefaultValue = "[1.0 1.0 1.0 1.0]",
        Help = "Phong tint and amount on $basetexture > 1 to scale phong, .a is diffuseComponent multiplier, 0=> remove diffuse, >1 => overbright diffuse",
    },
    ['PHONGAMOUNT2'] = {
        Type = "color",
        DefaultValue = "[1.0 1.0 1.0 1.0]",
        Help = "Phong tint and amount on $basetexture2 > 1 to scale phong, .a is diffuseComponent multiplier, 0=> remove diffuse, >1 => overbright diffuse",
    },
    ['DROPSHADOWOPACITY'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "Drop shadow between blended layers",
    },
    ['DROPSHADOWSCALE'] = {
        Type = "number",
        DefaultValue = "0.0125",
        Help = "Drop shadow size",
    },
    ['DROPSHADOWHIGHLIGHTSCALE'] = {
        Type = "number",
        DefaultValue = "0.025",
        Help = "Highlight size opposite drop shadow effect",
    },
    ['DROPSHADOWDEPTHEXAGGERATION'] = {
        Type = "number",
        DefaultValue = "4.0",
        Help = "Drop shadow depth exaggeration",
    },
    ['BASETEXTURETRANSFORM2'] = {
        Type = "matrix",
        DefaultValue = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
        Help = "$basetexture2 texcoord transform",
    },
    ['LAYERTINT1'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "color tint for layer 1",
    },
    ['LAYERTINT2'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "color tint for layer 2",
    },
    ['BLENDMODULATETRANSFORM'] = {
        Type = "matrix",
        DefaultValue = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
        Help = "$blendmodulatetexture texcoord transform",
    },
    ['ENVMAPMASK2'] = {
        Type = "texture",
        DefaultValue = "shadertest/shadertest_envmask",
        Help = "envmap mask 2",
    },
    ['ENVMAPMASKTRANSFORM2'] = {
        Type = "matrix",
        DefaultValue = "center .5 .5 scale 1 1 rotate 0 translate 0 0",
        Help = "$envmapmask2 texcoord transform",
    },
    ['NEWLAYERBLENDING'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Enable new layer blend math",
    },
    ['BLENDSOFTNESS'] = {
        Type = "number",
        DefaultValue = "0.5",
        Help = "Layer blend softness",
    },
    ['LAYERBORDERSTRENGTH'] = {
        Type = "number",
        DefaultValue = "0.5",
        Help = "Layer border strength",
    },
    ['LAYERBORDEROFFSET'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "Layer border offset",
    },
    ['LAYERBORDERSOFTNESS'] = {
        Type = "number",
        DefaultValue = "0.5",
        Help = "Layer border softness",
    },
    ['LAYERBORDERTINT'] = {
        Type = "vector",
        DefaultValue = "[1 1 1]",
        Help = "color tint for layer border",
    },
    ['LAYEREDGENORMAL'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Enable normals on layer edge",
    },
    ['LAYEREDGEPUNCHIN'] = {
        Type = "number",
        DefaultValue = "0",
        Help = "Invert normals on layer edge",
    },
    ['LAYEREDGESTRENGTH'] = {
        Type = "number",
        DefaultValue = "0.5",
        Help = "Layer edge normal strength",
    },
    ['LAYEREDGESOFTNESS'] = {
        Type = "number",
        DefaultValue = "0.5",
        Help = "Layer edge normal blend softness",
    },
    ['LAYEREDGEOFFSET'] = {
        Type = "number",
        DefaultValue = "0.0",
        Help = "Layer edge normal blend offset",
    },
}

matdyn.Proxies = {
    "CAbsProxy",
    "CAddProxy",
    "CClampProxy",
    "CDivideProxy",
    "CEconInspectPreviewTimeProxy",
    "CEmptyProxy",
    "CEntityRandomProxy",
    "CEntitySpeedProxy",
    "CEqualsProxy",
    "CExponentialProxy",
    "CFracProxy",
    "CGaussianNoiseProxy",
    "CIntProxy",
    "CLessOrEqualProxy",
    "CLinearRampProxy",
    "CModProxy",
    "CMultiplyProxy",
    "CPlayerPositionProxy",
    "CPlayerProximityProxy",
    "CPlayerSpeedProxy",
    "CPlayerTeamMatchProxy",
    "CPlayerViewProxy",
    "CRemapValClampedProxy",
    "CSineProxy",
    "CStatTrakDigitProxy",
    "CStatTrakDigitProxyForModelWeaponPreviewPanel",
    "CStatTrakIllumProxy",
    "CSubtractProxy",
    "CUniformNoiseProxy",
    "CWeaponLabelTextProxy",
    "CWeaponLabelTextProxyForModelWeaponPreviewPanel",
    "CWrapMinMaxProxy",
}

matdyn.ProxyParams = {
    "Shadow",
    "ShadowModel",
    "MaterialModify",
    "MaterialModifyAnimated",
    "PlayerLogo",
    "PlayerLogoModelPreview",
    "EntityOrigin",
    "SmokeOrigin",
    "EntityOriginAlyx",
    "Ep1IntroVortRefract",
    "Add",
    "Modulo",
    "Subtract",
    "Multiply",
    "Divide",
    "Clamp",
    "Sine",
    "Equals",
    "Frac",
    "Int",
    "LinearRamp",
    "UniformNoise",
    "GaussianNoise",
    "Exponential",
    "Abs",
    "Empty",
    "LessOrEqual",
    "WrapMinMax",
    "RemapValClamp",
    "TextureTransform",
    "MatrixRotate",
    "PlayerProximity",
    "PlayerColor",
    "WeaponColor",
    "PlayerTeamMatch",
    "PlayerView",
    "PlayerSpeed",
    "PlayerPosition",
    "EntitySpeed",
    "EntityRandom",
    "StatTrakDigit",
    "StatTrakDigitForModelWeaponPreview",
    "StatTrakIllum",
    "WeaponLabelText",
    "WeaponLabelTextPreview",
    "EconInspectPreviewTime",
    "LumCompare",
    "no_pixel_write",
    "downsample_non_hdr",
    "blurfilterx",
    "blurfiltery",
    "BloomAdd",
    "engine_post",
    "MotionBlur",
    "TeamIdMaterialProxy",
}

table.sort(matdyn.ProxyParams)